id: P005637
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-17 12:08:44.461941
source_metadata:
  id: bdr:W00KG010269
  title: རྒྱ་རོང་དགོན་བསམ་ལྷུན་དུང་སྒྲུབ་ཆེན་མོའི་ཞལ་འདོན་ཕྱོགས་སྒྲིགས་
  author: ''
  volumes:
    fb924cf01be54ea4a651bfa460a04b5b:
      image_group_id: I00KG010271
      title: ''
      volume_number: 1
      total_pages: 87
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
