id: P005637
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG010269
  title: རྒྱ་རོང་དགོན་བསམ་ལྷུན་དུང་སྒྲུབ་ཆེན་མོའི་ཞལ་འདོན་ཕྱོགས་སྒྲིགས་
  author: ''
  volumes:
    fb924cf01be54ea4a651bfa460a04b5b:
      image_group_id: I00KG010271
      title: ''
      volume_number: 1
      total_pages: 87
